server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native # 로컬파일정보
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/config-repo
        git:
          default-label: main
          # uri: file:///Users/djdj/Documents/config-repo
          uri: https://github.com/thisisdj/spring-cloud-config.git
          # private 저장소
          # username: []
          # password: []
management:
  endpoints:
    web:
      exposure:
        # busrefresh -> 액츄에이터 작동시 연결된 다른 서비스의 config도 갱신
        include: health, busrefresh
