server:
  port: 0

spring:
  application:
    name: USER-SERVICE
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  config:
    import: classpath:/bootstrap.yml # boot 2.4부터 부트스트랩 x
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce.

logging:
  level:
    com.microservice.client: DEBUG

#
#token:
#  expiration_time: 86400000
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
#  secret: user_token # 임의의 값